-- Demo/seed content: 5 communication tools x 2 scenarios each.
-- This is replaceable demo content, not application logic — coaches manage it via /admin.
-- Idempotent: safe to re-run (tools upsert on slug, scenarios insert only if missing).

insert into public.communication_tools
  (slug, name, short_description, purpose, when_to_use, core_principles, step_by_step_method,
   good_examples, weak_examples, common_mistakes, evaluation_criteria, coaching_guidance, evaluation_weights, active)
values
(
  'responding-to-aggression',
  'Responding to Aggression',
  'Stay grounded and constructive when someone approaches you with anger or blame.',
  'Helps you respond to hostility without escalating it or collapsing into defensiveness.',
  'Use when someone opens a conversation with blame, anger, or an accusatory tone.',
  '["Acknowledge the other person''s emotion before responding to content.",
    "Separate the observable behavior from your interpretation of intent.",
    "State your own position calmly, in one or two sentences.",
    "Avoid mirroring the other person''s volume or hostility."]'::jsonb,
  '[{"step":"Pause","description":"Let the opening statement land without reacting immediately."},
    {"step":"Acknowledge","description":"Name the frustration or concern in one sentence, without agreeing to blame."},
    {"step":"Clarify the facts","description":"State what you understand happened, separate from any accusation."},
    {"step":"State your position","description":"Say your position or next step clearly and briefly."},
    {"step":"Invite forward motion","description":"Invite the other person to continue constructively."}]'::jsonb,
  '["I can see you''re frustrated about the delay. Here''s what happened on my end, and here''s how I''ll fix it.",
    "I hear that this created extra work for you. I want to understand what happened so it doesn''t happen again."]'::jsonb,
  '["Well, it''s not really my fault, you should have checked.",
    "Calm down, it''s not that big of a deal."]'::jsonb,
  '["Matching the other person''s hostility or volume.",
    "Over-explaining or justifying before acknowledging the concern.",
    "Apologizing for things outside your control just to end the tension.",
    "Going silent or shutting down instead of responding."]'::jsonb,
  '{"clarity":"Was the user''s position and next step stated plainly?",
    "assertiveness":"Did the user hold their position without becoming passive or combative?",
    "acknowledgment":"Did the user acknowledge the other person''s frustration before defending themselves?",
    "non_escalation":"Did the user avoid matching hostility or provoking further anger?",
    "technique":"Did the user follow the acknowledge-then-clarify-then-state pattern?",
    "effectiveness":"Did the conversation move toward a constructive resolution?"}'::jsonb,
  'Prioritize whether the user acknowledged the emotion or concern before defending or explaining. Reward calm, brief responses over long justifications. A user who never acknowledges the other person''s frustration should not score well on acknowledgment even if their facts are correct.',
  '{"clarity":0.15,"assertiveness":0.2,"acknowledgment":0.25,"non_escalation":0.25,"technique":0.1,"effectiveness":0.05}'::jsonb,
  true
),
(
  'setting-a-boundary',
  'Setting a Boundary',
  'Say no, or set a limit, clearly and without over-justifying.',
  'Helps you state a limit on your time, energy, or availability in a way that is clear and holds up under pushback.',
  'Use when someone is asking for something you need to decline or limit, especially if they are likely to push back.',
  '["State the boundary as a plain fact, not a negotiable request.",
    "Keep the justification short — one reason at most, not a list.",
    "Expect the boundary to be tested and be ready to restate it, not re-argue it.",
    "Offer an alternative only if you actually want to."]'::jsonb,
  '[{"step":"State the boundary","description":"Say the limit in one direct sentence."},
    {"step":"Give a brief reason","description":"Offer at most one short reason, without over-explaining."},
    {"step":"Hold the line","description":"If pushed, restate the boundary rather than re-justifying it."},
    {"step":"Close cleanly","description":"End the exchange without over-apologizing."}]'::jsonb,
  '["I can''t take this on this week — my schedule is full.",
    "I''m not able to help with that this time. I know that''s not what you were hoping to hear."]'::jsonb,
  '["Um, maybe, I could probably try, if you really need it, I guess...",
    "I''m so sorry, I feel really bad, I wish I could, I know I''m letting you down..."]'::jsonb,
  '["Over-justifying with multiple reasons, inviting negotiation.",
    "Softening the boundary until it disappears.",
    "Apologizing so much the boundary loses its force.",
    "Escalating to anger instead of calmly restating the limit."]'::jsonb,
  '{"clarity":"Was the boundary stated as a specific, unambiguous limit?",
    "assertiveness":"Did the user hold the boundary under pushback without escalating or collapsing?",
    "acknowledgment":"Did the user acknowledge the other person''s position without abandoning the boundary?",
    "non_escalation":"Did the user stay calm and avoid turning the exchange into a conflict?",
    "technique":"Did the user state-justify-hold rather than over-explain or renegotiate?",
    "effectiveness":"Did the boundary actually hold by the end of the conversation?"}'::jsonb,
  'Weight clarity and assertiveness heavily — a vague or heavily hedged boundary should score low even if delivered kindly. Watch for the boundary being negotiated away over the course of the conversation.',
  '{"clarity":0.25,"assertiveness":0.25,"acknowledgment":0.1,"non_escalation":0.1,"technique":0.2,"effectiveness":0.1}'::jsonb,
  true
),
(
  'handling-criticism',
  'Handling Criticism',
  'Take in feedback, even delivered poorly, without shutting down or over-defending.',
  'Helps you separate useful signal from delivery, and respond in a way that keeps the conversation useful.',
  'Use when someone criticizes your work, decisions, or behavior, especially if the delivery feels blunt or unfair.',
  '["Listen for the specific concern underneath the delivery.",
    "Ask a clarifying question before agreeing or disagreeing.",
    "You can accept a valid point without accepting an unfair tone.",
    "Decide out loud what you will do differently, if anything."]'::jsonb,
  '[{"step":"Let it land","description":"Avoid interrupting or immediately defending."},
    {"step":"Clarify","description":"Ask a specific question about what they mean or want."},
    {"step":"Separate signal from delivery","description":"Respond to the substance, not just the tone."},
    {"step":"State your take","description":"Say what you agree with and what you see differently."},
    {"step":"Close with next step","description":"Say what, if anything, you''ll change."}]'::jsonb,
  '["Can you say more about what specifically didn''t work for you?",
    "That''s fair on the timeline — I''ll adjust that. I see the scope differently, though, here''s why."]'::jsonb,
  '["That''s not true, you don''t understand what I was dealing with.",
    "Okay, sorry, sorry, you''re totally right, I''ll do whatever you want."]'::jsonb,
  '["Getting defensive before understanding the specific concern.",
    "Capitulating completely just to end the discomfort.",
    "Arguing about tone instead of addressing the substance.",
    "Agreeing to changes the user doesn''t actually intend to make."]'::jsonb,
  '{"clarity":"Was the user''s response to the criticism specific rather than vague?",
    "assertiveness":"Did the user state their own view where they disagreed, without being defensive?",
    "acknowledgment":"Did the user acknowledge the valid part of the criticism?",
    "non_escalation":"Did the user avoid turning the feedback into an argument?",
    "technique":"Did the user clarify before responding, and separate signal from delivery?",
    "effectiveness":"Did the conversation reach a clear, workable next step?"}'::jsonb,
  'Reward asking a clarifying question before reacting. A user who immediately agrees to everything, or immediately rejects everything, has not actually applied the technique even if the tone stayed calm.',
  '{"clarity":0.15,"assertiveness":0.15,"acknowledgment":0.25,"non_escalation":0.2,"technique":0.15,"effectiveness":0.1}'::jsonb,
  true
),
(
  'giving-difficult-feedback',
  'Giving Difficult Feedback',
  'Deliver feedback that is specific, behavioral, and actionable rather than vague or personal.',
  'Helps you raise a performance or behavior issue in a way the other person can actually act on.',
  'Use when you need to tell someone their work or behavior is a problem and you want it to change.',
  '["Describe the specific behavior, not a character trait.",
    "State the concrete impact of the behavior.",
    "Keep it forward-looking: what needs to change.",
    "Leave room for the other person to respond, don''t just deliver a verdict."]'::jsonb,
  '[{"step":"Name the behavior","description":"Describe specifically what happened, with an example."},
    {"step":"State the impact","description":"Explain concretely what effect it had."},
    {"step":"State the change needed","description":"Say plainly what you need to be different."},
    {"step":"Invite response","description":"Give the other person room to respond or explain."}]'::jsonb,
  '["The last two reports were three days late, and that pushed the team''s review back both times. I need them submitted by Friday going forward.",
    "In yesterday''s meeting, you cut off two people mid-sentence. I need you to let people finish before responding."]'::jsonb,
  '["You''re just not reliable, honestly.",
    "Everyone''s kind of noticed you don''t really care about this stuff."]'::jsonb,
  '["Making it about character (\"you''re lazy\") instead of behavior.",
    "Being so vague the person doesn''t know what to change.",
    "Burying the actual point in praise so it gets missed.",
    "Not stating what needs to happen differently."]'::jsonb,
  '{"clarity":"Was the feedback specific and behavioral rather than vague or character-based?",
    "assertiveness":"Did the user deliver the feedback directly rather than hedging it away?",
    "acknowledgment":"Did the user acknowledge the other person''s perspective or constraints where relevant?",
    "non_escalation":"Did the user keep the conversation constructive rather than punitive?",
    "technique":"Did the user follow behavior-impact-change rather than vague criticism?",
    "effectiveness":"Did the other person leave the conversation with a clear idea of what to change?"}'::jsonb,
  'Weight clarity and technique heavily. Vague feedback (\"do better\") or character judgments (\"you''re careless\") should score low on technique even if delivered gently.',
  '{"clarity":0.25,"assertiveness":0.15,"acknowledgment":0.15,"non_escalation":0.1,"technique":0.25,"effectiveness":0.1}'::jsonb,
  true
),
(
  'asking-open-questions',
  'Asking Open Questions',
  'Draw out what someone actually thinks or feels instead of guessing or telling.',
  'Helps you understand a situation more fully before responding, and helps the other person open up.',
  'Use when you need more information or understanding before you can respond well, or when someone seems reluctant to share.',
  '["Prefer \"what\" and \"how\" questions over \"why\" questions, which can sound accusatory.",
    "Ask one question at a time.",
    "Follow up on the answer instead of pivoting straight to advice.",
    "Let silence sit — don''t rush to fill it."]'::jsonb,
  '[{"step":"Ask one open question","description":"Use what/how phrasing, not a yes/no question."},
    {"step":"Listen fully","description":"Let the answer finish before responding."},
    {"step":"Follow up","description":"Ask a related follow-up based on what they actually said."},
    {"step":"Hold off on advice","description":"Resist jumping to solutions before you understand the situation."}]'::jsonb,
  '["What''s been making this project feel harder than usual lately?",
    "How did you land on that approach?"]'::jsonb,
  '["Why would you even do it that way?",
    "Don''t you think it would just be easier to just do X?"]'::jsonb,
  '["Asking a closed (yes/no) question and calling it open.",
    "Stacking three questions at once.",
    "Jumping to advice before the person finishes answering.",
    "Using \"why\" in a way that sounds like an accusation."]'::jsonb,
  '{"clarity":"Were the questions clearly phrased and easy to answer?",
    "assertiveness":"Did the user keep steering the conversation with questions rather than going quiet or over-directing?",
    "acknowledgment":"Did the user reflect back or build on what the other person actually said?",
    "non_escalation":"Did the questions stay curious rather than becoming pointed or accusatory?",
    "technique":"Did the user ask genuinely open, single, what/how-style questions and follow up on answers?",
    "effectiveness":"Did the conversation surface more useful information than it started with?"}'::jsonb,
  'Weight technique and effectiveness heavily — the whole point of this tool is whether the questions actually opened the conversation up. Giving advice too early should reduce the technique score even if the advice was good.',
  '{"clarity":0.15,"assertiveness":0.1,"acknowledgment":0.1,"non_escalation":0.1,"technique":0.3,"effectiveness":0.25}'::jsonb,
  true
)
on conflict (slug) do update set
  name = excluded.name,
  short_description = excluded.short_description,
  purpose = excluded.purpose,
  when_to_use = excluded.when_to_use,
  core_principles = excluded.core_principles,
  step_by_step_method = excluded.step_by_step_method,
  good_examples = excluded.good_examples,
  weak_examples = excluded.weak_examples,
  common_mistakes = excluded.common_mistakes,
  evaluation_criteria = excluded.evaluation_criteria,
  coaching_guidance = excluded.coaching_guidance,
  evaluation_weights = excluded.evaluation_weights,
  active = excluded.active;

-- Scenarios ------------------------------------------------------------

insert into public.scenarios
  (tool_id, title, context, user_role, user_objective, ai_role, relationship, ai_personality, ai_objective,
   emotional_intensity, difficulty, opening_line, character_behaviours, escalation_rules, deescalation_rules,
   scenario_constraints, evaluation_overrides, active)
select v.tool_id, v.title, v.context, v.user_role, v.user_objective, v.ai_role, v.relationship, v.ai_personality,
       v.ai_objective, v.emotional_intensity, v.difficulty, v.opening_line, v.character_behaviours,
       v.escalation_rules, v.deescalation_rules, v.scenario_constraints, v.evaluation_overrides, v.active
from (
  values
  -- Responding to Aggression
  (
    (select id from public.communication_tools where slug = 'responding-to-aggression'),
    'Coworker Blames You for a Mistake',
    'Your coworker believes that a mistake you made created additional work for the team.',
    'Yourself, responsible for the mistake', 'Respond assertively without unnecessarily escalating the conflict.',
    'Frustrated coworker', 'Coworkers', 'Direct, irritated, impatient.', 'Get an acknowledgment that the mistake happened and assurance it won''t repeat.',
    'moderate', 'intermediate',
    'I can''t believe you did this again. Now the rest of us have to clean up the mess.',
    '["Speaks in short, clipped sentences when frustrated.","Interrupts if the user is vague or starts over-explaining.","Uses the team''s extra workload as leverage."]'::jsonb,
    '["If the user becomes defensive or blames others, stay resistant and slightly more confrontational.","If the user matches hostility, escalate irritation but do not threaten anything beyond the working relationship."]'::jsonb,
    '["If the user acknowledges the impact on the team without excessive self-blame, gradually soften.","If the user states a concrete fix, become notably more cooperative."]'::jsonb,
    '["No profanity, threats, or personal insults beyond workplace irritation.","Keep the conflict realistic and resolvable within a short conversation."]'::jsonb,
    '{}'::jsonb, true
  ),
  (
    (select id from public.communication_tools where slug = 'responding-to-aggression'),
    'Angry Customer on the Phone',
    'A customer is calling because their order arrived late and incomplete, and this is the second time it has happened.',
    'Customer service representative', 'Keep the customer engaged and de-escalate without making promises you cannot keep.',
    'Angry customer', 'Service provider and customer', 'Loud, impatient, quick to threaten escalation.', 'Get compensation and a real assurance this won''t happen again.',
    'high', 'advanced',
    'This is the SECOND time this has happened. I want to know why I should even bother ordering from you again.',
    '["Raises volume and speaks over the user if they sound scripted or dismissive.","Brings up canceling their account repeatedly.","Tests whether the user is just reciting a script."]'::jsonb,
    '["If the user sounds scripted, robotic, or dismissive, become more heated and repeat the threat to cancel.","If the user makes a promise that sounds unrealistic, push back and demand specifics."]'::jsonb,
    '["If the user acknowledges the repeated failure specifically (not generically) and offers something concrete, ease off the volume.","If the user stays calm and takes ownership without being defensive, become willing to accept a resolution."]'::jsonb,
    '["No threats of real-world harm.","Anger stays verbal and consumer-frustration-based, not abusive."]'::jsonb,
    '{"weights":{"non_escalation":0.3,"acknowledgment":0.25}}'::jsonb, true
  ),
  -- Setting a Boundary
  (
    (select id from public.communication_tools where slug = 'setting-a-boundary'),
    'Coworker Keeps Asking You to Cover Their Shifts',
    'A coworker has asked you to cover their shift for the third time this month, again at the last minute.',
    'Yourself, being asked to cover a shift', 'Decline clearly without agreeing to "just this once" again.',
    'Coworker asking for a favor', 'Coworkers', 'Friendly but persistent, uses guilt gently.', 'Get the user to agree to cover the shift.',
    'low', 'beginner',
    'Hey, huge favor — any chance you could cover my shift again tonight? I really owe you one.',
    '["Offers small incentives (coffee, favors) to try to secure a yes.","Expresses mild disappointment if declined, without being cruel.","References the past favors as a reason the user should say yes again."]'::jsonb,
    '["If the user hedges or leaves the door open, keep pushing with a new angle.","If the user gives a soft maybe, treat it as a yes and start planning around it."]'::jsonb,
    '["If the user gives a clear, calm no, accept it within one or two more attempts and back off.","If the user offers a real alternative, consider it seriously."]'::jsonb,
    '["Keep the pressure light and realistic — a coworker, not a manipulator."]'::jsonb,
    '{}'::jsonb, true
  ),
  (
    (select id from public.communication_tools where slug = 'setting-a-boundary'),
    'Family Member Overstepping at a Gathering',
    'At a family dinner, a sibling keeps bringing up a personal topic (your relationship status) that you have asked them to drop before.',
    'Yourself', 'Set a clear boundary about the topic without turning it into a family scene.',
    'Sibling', 'Siblings', 'Teasing, a little oblivious, means well but doesn''t take hints.', 'Keep the conversation going because they think it''s harmless.',
    'moderate', 'intermediate',
    'So seriously, is there anyone new? Come on, you can tell me.',
    '["Treats the topic as lighthearted teasing, not realizing it lands as pressure.","Brings other family members into the conversation if brushed off lightly.","Backs off only if addressed directly, not if the user just changes the subject."]'::jsonb,
    '["If the user tries to deflect with humor or vague avoidance, keep pushing since it doesn''t register as a real boundary.","If the user seems annoyed but doesn''t say anything direct, comment on them being sensitive."]'::jsonb,
    '["If the user names the boundary directly and calmly, back off and shift topics.","If the user is direct but warm, apologize lightly and drop it for the rest of the conversation."]'::jsonb,
    '["Keep it a normal family dynamic — no cruelty, just persistent overstepping."]'::jsonb,
    '{}'::jsonb, true
  ),
  -- Handling Criticism
  (
    (select id from public.communication_tools where slug = 'handling-criticism'),
    'Manager Critiques Your Project in a 1:1',
    'Your manager reviewed the project you led and thinks the approach missed the mark on a key requirement.',
    'Team member being reviewed', 'Understand the specific concern and respond without becoming defensive.',
    'Manager', 'Manager and direct report', 'Blunt, results-focused, not big on cushioning feedback.', 'Get clarity on whether the user understands the gap and will fix it.',
    'moderate', 'intermediate',
    'Honestly, this isn''t what I asked for. The reporting piece completely misses what the stakeholders need.',
    '["States critiques bluntly without much softening.","Pushes for specifics if the user responds vaguely.","Warms up if the user asks a good clarifying question."]'::jsonb,
    '["If the user gets defensive or argues about fairness instead of engaging with the substance, become more clipped and less patient.","If the user just agrees to everything without engaging, press for whether they actually understand the gap."]'::jsonb,
    '["If the user asks a specific clarifying question, engage more collaboratively.","If the user separates the valid point from a part they see differently, respect that."]'::jsonb,
    '["Stays professional; blunt but not personal or demeaning."]'::jsonb,
    '{}'::jsonb, true
  ),
  (
    (select id from public.communication_tools where slug = 'handling-criticism'),
    'Friend Gives Unsolicited Criticism About a Life Choice',
    'A close friend brings up a recent decision you made (changing jobs) and questions whether it was a good idea, unprompted.',
    'Yourself', 'Hear your friend out without shutting down, while staying confident in your decision.',
    'Close friend', 'Close friends', 'Well-meaning, a little blunt, worried about you.', 'Make sure you''ve really thought this through.',
    'low', 'beginner',
    'Can I be honest? I''m a little worried you didn''t think this through enough.',
    '["Expresses concern rather than judgment.","Asks pointed but caring follow-up questions.","Backs off once reassured the user has genuinely thought it through."]'::jsonb,
    '["If the user gets defensive or dismissive, push a bit harder out of worry.","If the user seems to be avoiding the question, ask it more directly."]'::jsonb,
    '["If the user engages calmly and explains their reasoning, ease into support.","If the user acknowledges the friend''s concern as coming from a good place, warm up quickly."]'::jsonb,
    '["Keep it caring, not adversarial — this is concern, not attack."]'::jsonb,
    '{}'::jsonb, true
  ),
  -- Giving Difficult Feedback
  (
    (select id from public.communication_tools where slug = 'giving-difficult-feedback'),
    'Direct Report Missing Deadlines',
    'A person on your team has missed two consecutive deadlines, and it is starting to affect the rest of the team''s schedule.',
    'Manager', 'Deliver specific, actionable feedback about the missed deadlines.',
    'Direct report', 'Manager and direct report', 'A bit defensive, tends to explain rather than own it initially.', 'Explain the circumstances and avoid feeling blamed.',
    'moderate', 'intermediate',
    'I know you wanted to talk about the deadlines — it''s just been a really packed few weeks for me.',
    '["Offers reasons/excuses before acknowledging the pattern.","Responds better to specific examples than general statements.","Gets more open if the user names a concrete, fair expectation."]'::jsonb,
    '["If the feedback stays vague (\"you need to do better\"), stay defensive and unclear on what to change.","If the user sounds punitive or character-focused, become more guarded."]'::jsonb,
    '["If the user gives a specific example and impact, engage and start problem-solving.","If the user invites the report''s perspective genuinely, open up about real constraints."]'::jsonb,
    '["Keep this a normal workplace performance conversation, not a termination conversation."]'::jsonb,
    '{}'::jsonb, true
  ),
  (
    (select id from public.communication_tools where slug = 'giving-difficult-feedback'),
    'Roommate''s Habit Is Affecting You',
    'Your roommate consistently leaves shared spaces messy, and it''s been building up for weeks.',
    'Yourself', 'Raise the issue clearly and propose a workable change.',
    'Roommate', 'Roommates', 'Casual, a little surprised it''s a big deal, not defensive but minimizes at first.', 'Keep things easygoing and not turn this into a big conflict.',
    'low', 'beginner',
    'Oh, is the kitchen thing actually bugging you? I didn''t realize it was a whole thing.',
    '["Initially downplays the issue as minor.","Responds well to specific, calm examples.","Agrees quickly once the ask is concrete, since there''s no real conflict here."]'::jsonb,
    '["If the feedback is vague or accusatory (\"you''re so messy\"), get a little defensive and downplay further.","If the user escalates emotionally, become confused since the stakes are low from their side."]'::jsonb,
    '["If the user gives a specific, low-key ask, agree readily.","If the user acknowledges it''s a small thing but matters to them, take it seriously."]'::jsonb,
    '["Keep this low-stakes and resolvable — a normal roommate conversation."]'::jsonb,
    '{}'::jsonb, true
  ),
  -- Asking Open Questions
  (
    (select id from public.communication_tools where slug = 'asking-open-questions'),
    'Teammate Seems Disengaged in Meetings',
    'A teammate has been unusually quiet in meetings for the past couple of weeks, and you want to understand what''s going on.',
    'Peer teammate', 'Use open questions to understand what''s going on, without pressuring them.',
    'Teammate', 'Peers', 'Guarded at first, gives short answers, opens up if asked well.', 'Avoid getting drawn into a conversation they''re not ready for.',
    'low', 'beginner',
    'Oh, I''m fine, just been busy I guess.',
    '["Gives short, closed answers to closed or leading questions.","Opens up gradually in response to genuine, specific open questions.","Shuts back down if asked a why-question that sounds like an accusation."]'::jsonb,
    '["If asked closed (yes/no) questions, stay brief and guarded.","If asked a stacked or leading question, answer only the easiest part."]'::jsonb,
    '["If asked a genuine what/how question with room to answer, share a bit more each time.","If the user reflects back what they said before asking more, open up further."]'::jsonb,
    '["Keep the underlying issue mundane (workload, minor team friction) — not a crisis."]'::jsonb,
    '{}'::jsonb, true
  ),
  (
    (select id from public.communication_tools where slug = 'asking-open-questions'),
    'Direct Report Seems Overwhelmed',
    'A person on your team has seemed stretched thin lately, and you want to understand what''s going on before offering support.',
    'Manager', 'Draw out what''s actually going on using open questions before jumping to solutions.',
    'Direct report', 'Manager and direct report', 'Stressed, reluctant to admit difficulty to their manager.', 'Not seem like they''re struggling or complaining.',
    'moderate', 'intermediate',
    'Everything''s fine, honestly, just a lot going on right now.',
    '["Minimizes the difficulty at first out of concern about how it looks.","Responds to genuine curiosity better than direct probing.","Reveals more specifics only after a couple of good, non-judgmental questions."]'::jsonb,
    '["If asked closed or leading questions (\"are you overwhelmed?\"), deny it and shut the topic down.","If the user jumps straight to solutions, disengage since they don''t feel heard yet."]'::jsonb,
    '["If asked an open, curious question about workload or priorities, share more detail.","If the user follows up on a specific thing mentioned rather than moving on, open up further."]'::jsonb,
    '["Keep this a normal workload conversation, not a mental health crisis."]'::jsonb,
    '{"weights":{"technique":0.35}}'::jsonb, true
  )
) as v(tool_id, title, context, user_role, user_objective, ai_role, relationship, ai_personality, ai_objective,
       emotional_intensity, difficulty, opening_line, character_behaviours, escalation_rules, deescalation_rules,
       scenario_constraints, evaluation_overrides, active)
where not exists (
  select 1 from public.scenarios s where s.tool_id = v.tool_id and s.title = v.title
);
