import type {
  AIProvider,
  EvaluationInput,
  EvaluationOutput,
  HintInput,
  HintOutput,
  InterlocutorReplyInput,
  InterlocutorReplyOutput,
} from "@/lib/ai/types";
import type { EvaluationLLMOutput } from "@/lib/coaching/schema";

const INTERLOCUTOR_REPLIES = [
  "I hear you, but I'm not sure that changes things from where I'm standing.",
  "Okay. Go on — what exactly are you asking me to do?",
  "That's fair, I hadn't thought about it that way.",
  "I'm still a little frustrated, honestly, but I'm listening.",
  "Alright. What would that actually look like in practice?",
];

const HINTS = [
  "Try acknowledging what they just said before making your own point.",
  "Say your position in one clear sentence, without adding three reasons.",
  "Ask a specific question before responding to the criticism.",
  "Separate what actually happened from how you're interpreting it.",
];

/**
 * Deterministic provider used automatically when no OPENAI_API_KEY is configured (see
 * /docs/DECISIONS.md). Good enough to exercise the full product loop and the Playwright e2e
 * test without any live model calls — not a stand-in for real conversation quality.
 */
export class MockAIProvider implements AIProvider {
  readonly name = "mock";

  async generateInterlocutorReply(input: InterlocutorReplyInput): Promise<InterlocutorReplyOutput> {
    const turnIndex = input.messages.filter((m) => m.role === "assistant").length;
    return { text: INTERLOCUTOR_REPLIES[turnIndex % INTERLOCUTOR_REPLIES.length] };
  }

  async generateHint(input: HintInput): Promise<HintOutput> {
    const index = input.messages.length % HINTS.length;
    return { text: HINTS[index] };
  }

  async generateEvaluation(input: EvaluationInput): Promise<EvaluationOutput> {
    const hasPreviousAttempt = input.userPrompt.includes("PREVIOUS ATTEMPT");

    const raw: EvaluationLLMOutput = {
      overall_summary:
        "(Demo mode — no AI provider configured.) This is a placeholder evaluation generated by the mock provider so the full practice loop can be exercised without an API key.",
      dimensions: {
        clarity: { score: 3, evidence: "Demo evidence excerpt.", explanation: "Placeholder explanation." },
        assertiveness: { score: 3, evidence: "Demo evidence excerpt.", explanation: "Placeholder explanation." },
        acknowledgment: { score: 3, evidence: "Demo evidence excerpt.", explanation: "Placeholder explanation." },
        non_escalation: { score: 4, evidence: "Demo evidence excerpt.", explanation: "Placeholder explanation." },
        technique: { score: 3, evidence: "Demo evidence excerpt.", explanation: "Placeholder explanation." },
        effectiveness: { score: 3, evidence: "Demo evidence excerpt.", explanation: "Placeholder explanation." },
      },
      strengths: [
        { point: "Stayed calm throughout the exchange.", evidence: "Demo mode placeholder." },
        { point: "Responded to what the other person actually said.", evidence: "Demo mode placeholder." },
      ],
      improvement_areas: [
        {
          issue: "This is placeholder feedback.",
          why_it_matters: "Configure OPENAI_API_KEY to get real, transcript-grounded coaching feedback.",
          suggestion: "See /docs/STATUS.md for setup instructions.",
          example: "",
        },
      ],
      next_focus: "Configure an AI provider to receive a real next-attempt focus.",
      comparison_notes: hasPreviousAttempt ? ["This is placeholder comparison text in demo mode."] : [],
    };

    return { raw };
  }
}
